"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

import { parseReportSnapshot, topThermalCells, type CoolingActionReport } from "../../lib/report-core";

const planName = (type: string) => type === "low_intervention" ? "Low intervention" : type === "balanced" ? "Balanced" : "Maximum cooling";
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);

export default function ReportPage() {
  const [report, setReport] = useState<CoolingActionReport | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => {
    const timer = window.setTimeout(() => {
      try {
        const raw = sessionStorage.getItem("coolcity-report-v4");
        if (!raw) throw new Error("Run the CoolCity policy workflow before opening a report.");
        setReport(parseReportSnapshot(JSON.parse(raw)));
      } catch (caught) {
        setError(caught instanceof Error ? caught.message : "Report data could not be loaded.");
      }
    }, 0);
    return () => window.clearTimeout(timer);
  }, []);
  if (error) return <main className="planner-report"><h1>CoolCity Planner Report</h1><p>{error}</p><Link href="/">Return to analysis</Link></main>;
  if (!report) return <main className="planner-report">Preparing report…</main>;
  const selected = report.selected_cell.properties;
  const plan = report.selected_plan;
  const incentive = report.incentive;
  const budget = report.budget_allocation;
  const weights = report.incentive_policy.scoreConfiguration.weights;
  return <main className="planner-report"><div className="report-actions no-print"><Link href="/">Back to map</Link><button type="button" onClick={() => window.print()}>Print / Save PDF</button></div>
    <header><span>COOLCITY AI · US URBAN COOLING POLICY INTELLIGENCE</span><h1>FortyGuard-Powered Planner Report</h1><p>Generated {new Date(report.generated_at).toLocaleString()}</p></header>
    <section><h2>1. Executive policy decision</h2><p><strong>{selected.cell_id}</strong> is the selected hotspot. The chosen <strong>{planName(plan.plan_type)}</strong> portfolio uses {plan.tree_count} trees, {plan.cool_roof_pct}% eligible-roof treatment, and {plan.cool_pavement_pct}% eligible-pavement treatment. It estimates {plan.central_estimate_c.toFixed(2)} C cooling with a remaining target gap of {plan.remaining_target_gap_c.toFixed(2)} C.</p></section>
    <section><h2>2. FortyGuard thermal diagnosis</h2><table><tbody><tr><th>Policy assessment area</th><td>{report.area_m2.toLocaleString(undefined, { maximumFractionDigits: 0 })} m²</td></tr><tr><th>Source</th><td>Original FortyGuard Temperature AI provider result · {report.analysis.cached ? "server cache reused" : "new provider response"}</td></tr><tr><th>Cells / AOI mean</th><td>{report.analysis.summary.cell_count} / {report.analysis.summary.mean_temperature_c.toFixed(2)} C</td></tr><tr><th>Analysis ID</th><td>{report.analysis.analysis_id}</td></tr></tbody></table></section>
    <section><h2>3. Hottest FortyGuard cells</h2><table><thead><tr><th>Cell</th><th>Temperature</th><th>Anomaly</th><th>Rank</th><th>Priority</th></tr></thead><tbody>{topThermalCells(report).map((cell) => <tr key={cell.properties.cell_id}><td>{cell.properties.cell_id}</td><td>{cell.properties.temperature_c.toFixed(2)} C</td><td>{cell.properties.thermal_delta_c.toFixed(2)} C</td><td>{cell.properties.heat_rank}/{cell.properties.heat_rank_total}</td><td>{cell.properties.thermal_priority_score.toFixed(1)}</td></tr>)}</tbody></table></section>
    <section><h2>4. Selected hotspot</h2><table><tbody><tr><th>Cell</th><td>{selected.cell_id}</td></tr><tr><th>FortyGuard observed temperature</th><td>{selected.temperature_c.toFixed(2)} C</td></tr><tr><th>Anomaly / percentile</th><td>{selected.thermal_delta_c.toFixed(2)} C / {selected.thermal_percentile.toFixed(1)}th</td></tr><tr><th>Peak / exceedance / persistence</th><td>{selected.peak_heat_time ?? "Not analyzed"} / {selected.exceedance_hours === null ? "Not analyzed" : `${selected.exceedance_hours} h`} / {selected.persistence_hours === null ? "Not analyzed" : `${selected.persistence_hours} h`}</td></tr></tbody></table></section>
    <section><h2>5. Urban vegetation context</h2><p>{Number(selected.tree_cover_pct ?? 0).toFixed(1)}% tree cover, {Number(selected.green_vegetation_pct ?? 0).toFixed(1)}% green vegetation, {Number(selected.built_up_pct ?? 0).toFixed(1)}% built-up, and {Number(selected.bare_sparse_pct ?? 0).toFixed(1)}% bare/sparse.</p><p>ESA WorldCover 2021 is a historical land-cover baseline, not live vegetation.</p></section>
    <section><h2>6. Government cooling target</h2><table><tbody><tr><th>Current</th><td>{plan.fortyguard_observed_temperature_c.toFixed(2)} C</td></tr><tr><th>Government target</th><td>{report.government_target_temperature_c.toFixed(2)} C</td></tr><tr><th>Required reduction</th><td>{plan.required_reduction_c.toFixed(2)} C</td></tr><tr><th>Status</th><td>{plan.target_achieved ? "Target achieved by screening estimate" : `Target not fully achieved; ${plan.remaining_target_gap_c.toFixed(2)} C gap remains`}</td></tr></tbody></table></section>
    <section><h2>7. Recommended policy portfolios</h2><table><thead><tr><th>Plan</th><th>Trees</th><th>Roofs</th><th>Pavement</th><th>Reduction</th><th>Target gap</th></tr></thead><tbody>{report.optimization.plans.map((candidate) => <tr key={candidate.plan_type}><td>{planName(candidate.plan_type)}</td><td>{candidate.tree_count}</td><td>{candidate.cool_roof_pct}%</td><td>{candidate.cool_pavement_pct}%</td><td>{candidate.central_estimate_c.toFixed(2)} C</td><td>{candidate.remaining_target_gap_c.toFixed(2)} C</td></tr>)}</tbody></table></section>
    <section><h2>8. Modeled temperature impact</h2><p><strong>CURRENT — FortyGuard observed temperature: {plan.fortyguard_observed_temperature_c.toFixed(2)} C.</strong></p><p><strong>AFTER POLICY — CoolCity modeled estimate: {plan.modeled_post_intervention_temperature_c.toFixed(2)} C.</strong></p><p>Estimated reduction {plan.central_estimate_c.toFixed(2)} C; uncertainty range {plan.lower_estimate_c.toFixed(2)}–{plan.upper_estimate_c.toFixed(2)} C; confidence {plan.confidence}. Tree {plan.tree_cooling_c.toFixed(2)} C, cool roof {plan.cool_roof_cooling_c.toFixed(2)} C, cool pavement {plan.cool_pavement_cooling_c.toFixed(2)} C before conservative interaction adjustment.</p><p><strong>The modeled after-policy value is not a FortyGuard forecast.</strong></p></section>
    <section><h2>9. CO2 sequestration co-benefit</h2><p><strong>{plan.estimated_annual_co2_sequestration_kg.toLocaleString()} kg CO2/year</strong> at effective mature canopy. {plan.carbon_disclaimer}</p></section>
    <section><h2>10. Cooling incentive policy</h2>{incentive ? <><table><tbody><tr><th>Policy type</th><td>{incentive.policyType}</td></tr><tr><th>FortyGuard Thermal Priority</th><td>{incentive.fortyGuardThermalPriority.toFixed(1)} / 100</td></tr><tr><th>Modeled cooling benefit</th><td>{incentive.modeledCoolingBenefitC.toFixed(2)} C</td></tr><tr><th>Cooling Incentive Score</th><td>{incentive.coolingIncentiveScore.toFixed(1)} / 100</td></tr><tr><th>Government-configurable tier</th><td>{incentive.tierLabel}</td></tr><tr><th>Illustrative maximum credit</th><td>Up to {money(incentive.illustrativeMaximumCredit)}</td></tr><tr><th>Verification status</th><td>{incentive.verificationStatus}</td></tr></tbody></table><h3>Policy explanation</h3><ul>{incentive.explanation.map((reason) => <li key={reason}>{reason}</li>)}</ul><p><strong>Example policy configuration:</strong> thermal burden {weights.thermalBurden * 100}%, modeled cooling {weights.coolingBenefit * 100}%, durability {weights.durability * 100}%; cooling reference {report.incentive_policy.scoreConfiguration.referenceCoolingC.toFixed(1)} C.</p><p>{incentive.disclaimer}</p></> : <p>No incentive assessment was produced because the selected portfolio has no positive modeled intervention benefit.</p>}</section>
    {budget ? <section><h2>11. City incentive allocation</h2><table><tbody><tr><th>Budget</th><td>{money(budget.totalBudget)}</td></tr><tr><th>Sites evaluated / recommended</th><td>{budget.sitesEvaluated} / {budget.sitesFunded}</td></tr><tr><th>Funding allocated</th><td>{money(budget.allocatedBudget)}</td></tr><tr><th>Remaining budget</th><td>{money(budget.remainingBudget)}</td></tr><tr><th>Aggregate modeled site-level cooling</th><td>{budget.estimatedAggregateModeledCoolingC.toFixed(2)} C</td></tr><tr><th>Aggregate annual CO2 sequestration</th><td>{budget.estimatedAggregateAnnualCo2SequestrationKg.toLocaleString()} kg CO2/year</td></tr></tbody></table><p>{budget.disclaimer}</p></section> : null}
    <section><h2>{budget ? "12" : "11"}. Evidence and model methodology</h2><p>Evidence database: {plan.evidence_database_id}. {plan.interaction_method}</p><p>Local calibration used: {plan.local_calibration.local_calibration_used ? `yes, bounded multiplier ${plan.local_calibration.multiplier}×` : "no; published evidence model used"}. n={plan.local_calibration.sample_count}, temperature range={plan.local_calibration.temperature_range_c} C, tree-cover range={plan.local_calibration.tree_cover_range_pct} pp, R²={plan.local_calibration.r_squared ?? "N/A"}, RMSE={plan.local_calibration.rmse_c ?? "N/A"} C.</p></section>
    <section><h2>{budget ? "13" : "12"}. Uncertainty</h2><p>{plan.disclaimer}</p>{plan.extrapolation_warnings.length ? <ul>{plan.extrapolation_warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul> : <p>No configured evidence-range extrapolation warning was triggered.</p>}</section>
    <section><h2>{budget ? "14" : "13"}. Incentive safeguards</h2><p>Higher observed heat can increase assistance priority, never tax liability. CoolCity uses no protected personal attributes, does not verify proposed physical work automatically, and does not make a legal tax, payment, or funding decision. Municipal review remains required.</p></section>
    <section><h2>{budget ? "15" : "14"}. Limitations</h2><p>This is a policy-screening tool, not engineering design or a causal field experiment. Roof and pavement percentages are policy scenario variables, not measured eligible areas. The selected geometry is a policy assessment area, not a legal parcel. WorldCover is historical. Canopy maturity, survival, ownership, utilities, soil, implementation cost, maintenance, and future climate require field and professional review.</p></section>
  </main>;
}
